source "https://rubygems.org"

# Specify your gem's dependencies in cli_charities.gemspec


gem 'httparty', '~> 0.18.1'

gem 'require_all', '~> 3.0'

gem 'pry', '~> 0.13.1'

gem 'pry-byebug', '~> 3.9'

gem "rake", "~> 12.0"

